# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

environment:
  nodejs_version: "20" # версия node.js

branches:
  only:
    - main # ветка git

cache: node_modules # кеширование

install:
  - npm install # установка зависимостей

build: off # отключение встроенной в appveyor системы сборки

build_script:
  - npm run build # сборка проекта

test_script:
  - npm run lint && npm test # скрипт тестирования